ASSUME CS: CODE 
CODE SEGMENT 
START: 
	MOV DX, 8006H 
	MOV AL,80H 
	OUT DX,AL 
	MOV DX,8000H 
	BACK: OUT DX,AL 
	CALL DELAY 
	RO1 AL,01H 
	JMP BACK 
    DELAY: MOV CX, 00FFH 
    L1: DEC CX 
	JNZ L1 
	RET 
	INT 03H 
	CODE ENDS 
	END START